version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "processing"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "masterkey"
    volumes:
      - .:/docker-entrypoint-processing.d
    ports:
      - "5432:5432"