server:
  port: 9000
spring:
  application:
    name: auth-service
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: password
    driverClassName: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db
    url: jdbc:postgresql://localhost:5433/postgres
    user: postgres
    password: password
logging:
  level:
    root: debug